

version: '2'

services: 
    # node-exporter (host metrics collector)
    # node-exporter:
    #   image: stefanprodan/swarmprom-node-exporter:v0.15.2
    #   environment:
    #     - NODE_ID={{.Node.ID}}
    #   volumes:
    #     - /proc:/host/proc:ro
    #     - /sys:/host/sys:ro
    #     - /:/rootfs:ro
    #     - /etc/hostname:/etc/nodename
    #   command:
    #     - '--path.sysfs=/host/sys'
    #     - '--path.procfs=/host/proc'
    #     - '--collector.textfile.directory=/etc/node-exporter/'
    #     - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    #     # no collectors are explicitely enabled here, because the defaults are just fine,
    #     # see https://github.com/prometheus/node_exporter
    #     # disable ipvs collector because it barfs the node-exporter logs full with errors on my centos 7 vm's
    #     - '--no-collector.ipvs'
    node-exporter:
      image: prom/node-exporter:
      environment:
        - NODE_ID={{.Node.ID}}
      ports:
        - 9100:9100