version: '2.3'

services:

  prometheus:
    image: prom/prometheus:v2.8.1
    container_name: monitoring_prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    expose:
      - 9090
    ports:
      - 9090:9090
    mem_limit: 128m
    labels:
      org.label-schema.group: "monitoring"

  node-exporter:
    image: prom/node-exporter:v0.17.0
    container_name: monitoring_node_exporter
    restart: unless-stopped
    ports:
      - 9100:9100
    mem_limit: 64m
    labels:
      org.label-schema.group: "monitoring"

  cadvisor:
    image: google/cadvisor:v0.33.0
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    mem_limit: 64m
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    image: grafana/grafana:6.1.3
    container_name: grafana
    restart: always
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
        - "3000:3000"
    environment:
        - GF_INSTALL_PLUGINS=grafana-piechart-panel,jdbranham-diagram-panel
        - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
        - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
        - GF_USERS_ALLOW_SIGN_UP=false
    mem_limit: 128m
    labels:
      org.label-schema.group: "monitoring"